dokkebi_han.py binary\E1.FNT   binary\H01.FNT ! ! "HE±½Àº´Þ²Ã"     "HEGulgeunDalkkol"
dokkebi_han.py !               binary\H02.FNT ! ! "HE°¡´Â´Þ²Ã"     "HEGaneunDalkkol"
dokkebi_han.py binary\E3.FNT   binary\H03.FNT ! ! "HE¹ö±Ý´Þ²Ã"     "HEBeogeumDalkkol"
dokkebi_han.py binary\E2.FNT   binary\H04.FNT ! ! "HEµÕ±Ù¸ð²Ã"     "HEDunggeunmokkol"
dokkebi_han.py binary\E2.FNT   binary\H05.FNT ! ! "HEÂªÀºµÕ±Ù¸ð²Ã" "HEJjalbeunDunggeunmokkol"
dokkebi_han.py binary\E4_2.FNT binary\H06.FNT ! ! "HE¸þ²Ã"         "HEMoekkol"
dokkebi_han.py binary\E4_3.FNT binary\H07.FNT ! ! "HEÂªÀº¸þ²Ã"     "HEJjalbeunMoekkol"
dokkebi_han.py binary\E8.FNT   binary\H08.FNT ! ! "HEÁßÅÂ¼¼¸ð²Ã"   "HEJungtaesemokkol"
dokkebi_han.py binary\E4_2.FNT binary\H09.FNT ! ! "HE»¸À½²Ã"       "HEPpeodeumkkol"
dokkebi_han.py binary\E4_3.FNT binary\H10.FNT ! ! "HEÂªÀº»¸À½²Ã"    "HEJjalbeunPpeodeumkkol"
dokkebi_han.py binary\E6.FNT   binary\H11.FNT ! ! "HE»ßÄ§²Ã"       "HEPpichimkkol"
dokkebi_han.py binary\E4_3.FNT binary\H12.FNT ! ! "HEÀÛÀº»ßÄ§²Ã"    "HEJageunppichimkkol"
dokkebi_han.py binary\E3.FNT   binary\H13.FNT ! ! "HEÇ®ÀÙ²Ã"        "HEPuripkkol"
dokkebi_han.py binary\E5.FNT   binary\H14.FNT ! ! "HE´ë³ª¹«²Ã"      "HEDaenamukkol"
dokkebi_han.py binary\E4_2.FNT binary\H15.FNT ! ! "HEÆ÷°·²Ã"        "HEPogaemkkol"
pause